### ISSUE TITLE
Crash on adding a link

### ISSUE THREAD

**Issue by igorlanko** [miniware/organic_software_directory#29]
Tried adding this link https://goatcounter.com, so on the details screen:
![CleanShot 2024-04-27 at 18 37 44](https://github.com/miniware/organic_software_directory/assets/31314207/200eeb6d-7552-4ca4-87fe-8611aaf85f7b)

it looks like the icon URL is not validated? Nonetheless reformatting it manually to `https://` doesn't help and after clicking on the `Create Listing`:
![CleanShot 2024-04-27 at 18 39 06](https://github.com/miniware/organic_software_directory/assets/31314207/37e8baff-9699-46c7-931e-3f35f30d2200)

**Comment by nickisnoble** [comment]
@igorlanko great catch! Should be good to post it now.

There's some polish still to do so those `//` paths won't fail in the future, but now it's not gamebreaking.
